### ISSUE TITLE
Prepare Release - Please Test!

### ISSUE THREAD

**Issue by cmather** [iron-meteor/iron-cli#105]
@scott-mcpherson et all,

I'd love to do a release today. Mind giving the new create/migrate commands a spin. And checking out the coffee stuff? If it's working well, I'll release a new version!

**Comment by scott-mcpherson** [comment]
I just ran into an issue with the migrate command. Here are the steps I took.

1) created a new app using em: `$ em create test --js=coffee --css-false`
2) installed iron:router and coffeescript
3) create a home route
4) ran the iron migrate command, which threw an error
```
Error: ENOTEMPTY, directory not empty 'app/lib/router'
    at Object.fs.rmdirSync (fs.js:617:18)
    at Command.<anonymous> (/Users/scotty/Develop/Utilities/iron/lib/commands/migrate.js:79:46)
    at Command.invoke (/Users/scotty/Develop/Utilities/iron/lib/command.js:111:26)
    at Command.run (/Users/scotty/Develop/Utilities/iron/lib/command.js:91:21)
    at Command.runSubCommand (/Users/scotty/Develop/Utilities/iron/lib/command.js:154:11)
    at Command.<anonymous> (/Users/scotty/Develop/Utilities/iron/lib/iron.js:66:17)
    at Command.invoke (/Users/scotty/Develop/Utilities/iron/lib/command.js:111:26)
    at Command.run (/Users/scotty/Develop/Utilities/iron/lib/command.js:91:21)
    at /Users/scotty/Develop/Utilities/iron/bin/iron:11:8
```
It looks like `rmdirSync` on line 79 in commands/migrate.js is expecting an empty directory. Not 100% sure if that's the root of the Error though @cmather .

**Comment by scott-mcpherson** [comment]
Actually, coffeescript is not supported with the migrate command right?

**Comment by cmather** [comment]
Hmm yeah I only wrote one for javascript. It should probably be a little more intelligent. Can you see if it works with a regular javascript app. Perhaps for now we can put a notice that says this only migrates javascript and not coffeescript for now.

**Comment by scott-mcpherson** [comment]
Yeah, it works with javascript without any problems.

**Comment by lirbank** [comment]
Found a minor doc error https://github.com/iron-meteor/iron-cli/pull/106

**Comment by cmather** [comment]
1.1.0 released! thanks for the help!
