### ISSUE TITLE
Migration error

### ISSUE THREAD

**Issue by Francescu** [iron-meteor/iron-cli#117]
When I try to migrate from `em` using `iron migrate` I have the following error:

```
/usr/local/lib/node_modules/iron-meteor/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: ENOTEMPTY, directory not empty 'app/lib/router'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:715:18)
    at Command.<anonymous> (/usr/local/lib/node_modules/iron-meteor/lib/commands/migrate.js:79:46)
    at Command.invoke (/usr/local/lib/node_modules/iron-meteor/lib/command.js:111:26)
    at Command.run (/usr/local/lib/node_modules/iron-meteor/lib/command.js:91:21)
    at Command.runSubCommand (/usr/local/lib/node_modules/iron-meteor/lib/command.js:154:11)
    at Command.<anonymous> (/usr/local/lib/node_modules/iron-meteor/lib/iron.js:66:17)
    at Command.invoke (/usr/local/lib/node_modules/iron-meteor/lib/command.js:111:26)
    at Command.run (/usr/local/lib/node_modules/iron-meteor/lib/command.js:91:21)
    at /usr/local/lib/node_modules/iron-meteor/bin/iron:11:8
```

I guess it does most of the job as there is a new `app/` structure.

**Comment by scott-mcpherson** [comment]
Hey @Francescu, were you by any chance using CoffeeScript?

**Comment by Francescu** [comment]
Yep.

**Comment by Francescu** [comment]
Should I add 
```javascript
if (this.isFile('app/lib/router/routes.coffee')) fs.renameSync('app/lib/router/routes.coffee', 'app/lib/routes.coffee');
``` 
in https://github.com/iron-meteor/iron-cli/blob/master/lib/commands/migrate.js#L78 ?

**Comment by cmather** [comment]
I think this has been fixed in the release going out today.
