### ISSUE TITLE
Crashing with Latest Meteor 1.0.4.1 update.

### ISSUE THREAD

**Issue by delay** [iron-meteor/iron-cli#126]
When I create a default project with iron-cli it crashes on start.

To duplicate:

iron create YOURAPP
then run it with iron and crash on start.

=> Started proxy.                             
=> Started MongoDB.                           
W20150318-08:29:01.699(-5)? (STDERR)          
=> Exited with code: 8
W20150318-08:29:01.737(-5)? (STDERR) /Users/delay/.meteor/packages/meteor-tool/.1.0.43.1pxcg8d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150318-08:29:01.737(-5)? (STDERR)            				throw(ex);
W20150318-08:29:01.737(-5)? (STDERR)            				      ^
W20150318-08:29:01.737(-5)? (STDERR) Error: Cannot find module '/Users/delay/Dropbox/Programming/HOA/app/.meteor/local/build/programs/server/npm/iron_router/node_modules/body-parser'
W20150318-08:29:01.738(-5)? (STDERR)     at Function.Module._resolveFilename (module.js:338:15)
W20150318-08:29:01.738(-5)? (STDERR)     at Function.Module._load (module.js:280:25)
W20150318-08:29:01.738(-5)? (STDERR)     at Module.require (module.js:364:17)
W20150318-08:29:01.738(-5)? (STDERR)     at require (module.js:380:17)
W20150318-08:29:01.738(-5)? (STDERR)     at Object.Npm.require (/Users/delay/Dropbox/Programming/HOA/app/.meteor/local/build/programs/server/boot.js:142:18)
W20150318-08:29:01.738(-5)? (STDERR)     at assert (packages/iron:router/lib/body_parser_server.js:1:1)
W20150318-08:29:01.738(-5)? (STDERR)     at /Users/delay/Dropbox/Programming/HOA/app/.meteor/local/build/programs/server/packages/iron_router.js:1269:4
W20150318-08:29:01.738(-5)? (STDERR)     at /Users/delay/Dropbox/Programming/HOA/app/.meteor/local/build/programs/server/packages/iron_router.js:1455:3
W20150318-08:29:01.739(-5)? (STDERR)     at /Users/delay/Dropbox/Programming/HOA/app/.meteor/local/build/programs/server/boot.js:222:10
W20150318-08:29:01.739(-5)? (STDERR)     at Array.forEach (native)
W20150318-08:29:03.215(-5)? (STDERR)          
W20150318-08:29:03.216(-5)? (STDERR) /Users/delay/.meteor/packages/meteor-tool/.1.0.43.1pxcg8d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150318-08:29:03.216(-5)? (STDERR) 						throw(ex);
W20150318-08:29:03.216(-5)? (STDERR) 						      ^
W20150318-08:29:03.231(-5)? (STDERR) Error: Cannot find module '/Users/delay/Dropbox/Programming/HOA/app/.meteor/local/build/programs/server/npm/iron_router/node_modules/body-parser'
W20150318-08:29:03.231(-5)? (STDERR)     at Function.Module._resolveFilename (module.js:338:15)
W20150318-08:29:03.231(-5)? (STDERR)     at Function.Module._load (module.js:280:25)
W20150318-08:29:03.231(-5)? (STDERR)     at Module.require (module.js:364:17)
W20150318-08:29:03.231(-5)? (STDERR)     at require (module.js:380:17)
W20150318-08:29:03.231(-5)? (STDERR)     at Object.Npm.require (/Users/delay/Dropbox/Programming/HOA/app/.meteor/local/build/programs/server/boot.js:142:18)
W20150318-08:29:03.231(-5)? (STDERR)     at assert (packages/iron:router/lib/body_parser_server.js:1:1)
W20150318-08:29:03.231(-5)? (STDERR)     at /Users/delay/Dropbox/Programming/HOA/app/.meteor/local/build/programs/server/packages/iron_router.js:1269:4
W20150318-08:29:03.231(-5)? (STDERR)     at /Users/delay/Dropbox/Programming/HOA/app/.meteor/local/build/programs/server/packages/iron_router.js:1455:3
W20150318-08:29:03.231(-5)? (STDERR)     at /Users/delay/Dropbox/Programming/HOA/app/.meteor/local/build/programs/server/boot.js:222:10
W20150318-08:29:03.231(-5)? (STDERR)     at Array.forEach (native)
=> Exited with code: 8
W20150318-08:29:04.659(-5)? (STDERR)          
W20150318-08:29:04.660(-5)? (STDERR) /Users/delay/.meteor/packages/meteor-tool/.1.0.43.1pxcg8d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150318-08:29:04.660(-5)? (STDERR) 						throw(ex);
W20150318-08:29:04.660(-5)? (STDERR) 						      ^
W20150318-08:29:04.675(-5)? (STDERR) Error: Cannot find module '/Users/delay/Dropbox/Programming/HOA/app/.meteor/local/build/programs/server/npm/iron_router/node_modules/body-parser'
W20150318-08:29:04.675(-5)? (STDERR)     at Function.Module._resolveFilename (module.js:338:15)
W20150318-08:29:04.675(-5)? (STDERR)     at Function.Module._load (module.js:280:25)
W20150318-08:29:04.675(-5)? (STDERR)     at Module.require (module.js:364:17)
W20150318-08:29:04.675(-5)? (STDERR)     at require (module.js:380:17)
W20150318-08:29:04.675(-5)? (STDERR)     at Object.Npm.require (/Users/delay/Dropbox/Programming/HOA/app/.meteor/local/build/programs/server/boot.js:142:18)
W20150318-08:29:04.675(-5)? (STDERR)     at assert (packages/iron:router/lib/body_parser_server.js:1:1)
W20150318-08:29:04.675(-5)? (STDERR)     at /Users/delay/Dropbox/Programming/HOA/app/.meteor/local/build/programs/server/packages/iron_router.js:1269:4
W20150318-08:29:04.675(-5)? (STDERR)     at /Users/delay/Dropbox/Programming/HOA/app/.meteor/local/build/programs/server/packages/iron_router.js:1455:3
W20150318-08:29:04.675(-5)? (STDERR)     at /Users/delay/Dropbox/Programming/HOA/app/.meteor/local/build/programs/server/boot.js:222:10
W20150318-08:29:04.676(-5)? (STDERR)     at Array.forEach (native)
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.

**Comment by delay** [comment]
oops sorry nevermind.  I uninstalled and reinstalled meteor and the problem went away.  Something must of messed up during the update.
