### ISSUE TITLE
next.js generator isn't available

### ISSUE THREAD

**Issue by fredericlefeurmou** [iron-meteor/iron-cli#177]
As explained in the doc, I try to create a new project using es6: `--js=js|coffee|next.js`
but it doesn't work. I get the following error:

```
Error: Unsported js engine: next
    at withValidation (/usr/local/lib/node_modules/iron-meteor/lib/config.js:40:11)
    at Object.CurrentConfig.withValue (/usr/local/lib/node_modules/iron-meteor/lib/config.js:64:17)
    at Command.<anonymous> (/usr/local/lib/node_modules/iron-meteor/lib/commands/init.js:61:24)
    at Command.invoke (/usr/local/lib/node_modules/iron-meteor/lib/command.js:111:26)
    at Command.<anonymous> (/usr/local/lib/node_modules/iron-meteor/lib/commands/create.js:15:37)
    at Command.invoke (/usr/local/lib/node_modules/iron-meteor/lib/command.js:111:26)
    at Command.run (/usr/local/lib/node_modules/iron-meteor/lib/command.js:91:21)
    at Command.runSubCommand (/usr/local/lib/node_modules/iron-meteor/lib/command.js:154:11)
    at Command.<anonymous> (/usr/local/lib/node_modules/iron-meteor/lib/iron.js:66:17)
    at Command.invoke (/usr/local/lib/node_modules/iron-meteor/lib/command.js:111:26)
```

P.S. It works with coffee

**Comment by scottmcpherson** [comment]
How about --js=es6 ?

**Comment by fredericlefeurmou** [comment]
Thanks, it worked. I updated the doc https://github.com/iron-meteor/iron-cli/pull/178/files

**Comment by chrisbutler** [comment]
aha! thanks @fredericlefeurmou
