### ISSUE TITLE
Not able to install iron-meteor on mac os x 10.11

### ISSUE THREAD

**Issue by kelsadita** [iron-meteor/iron-cli#221]
I am trying to install *iron-meteor* on mac os 10.11. But its failing with following error,

```
➜  npm install -g iron-meteor
/Users/kalpeshadhatrao/.nvm/versions/node/v5.0.0/bin/iron -> /Users/kalpeshadhatrao/.nvm/versions/node/v5.0.0/lib/node_modules/iron-meteor/bin/iron

> fibers@1.0.7 install /Users/kalpeshadhatrao/.nvm/versions/node/v5.0.0/lib/node_modules/iron-meteor/node_modules/fibers
> node build.js || nodejs build.js

  CXX(target) Release/obj.target/fibers/src/fibers.o
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/fibers.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/fibers.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/kalpeshadhatrao/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/Users/kalpeshadhatrao/.nvm/versions/node/v5.0.0/bin/node" "/Users/kalpeshadhatrao/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Users/kalpeshadhatrao/.nvm/versions/node/v5.0.0/lib/node_modules/iron-meteor/node_modules/fibers
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
Build failed
sh: nodejs: command not found
npm WARN install:fibers fibers@1.0.7 install: `node build.js || nodejs build.js`
npm WARN install:fibers spawn ENOENT
/Users/kalpeshadhatrao/.nvm/versions/node/v5.0.0/lib
└── (empty)
```

**nodejs version**: v5.0.0
**npm version**: 3.3.6

**Comment by rkrishnan2012** [comment]
Do you have xcode command line tools installed?

**Comment by robbyking3** [comment]
any update on this?

**Comment by derekmacrae** [comment]
You could maybe try downloading the zipped files, changing the fibers version to 1.0.8 in the package.json file and run a local "npm install -g" to see if that fixes it. I had a fail on Windows that was fixed by moving up to the latest version of fibers.

**Comment by chrisbutler** [comment]
@kelsadita @rkrishnan2012 @robbyking3 version 1.5.2 is up on NPM now, which fixes this. thanks @derekmacrae
