### ISSUE TITLE
Impossible to install Iron

### ISSUE THREAD

**Issue by Loschcode** [iron-meteor/iron-cli#223]
I'm doing `npm install -g iron-meteor` on my terminal ans it outputs ..

```
root@PantouflesNginx:/var/www# npm install -g iron-meteor
-
> fibers@1.0.7 install /root/.nvm/v0.10.40/lib/node_modules/iron-meteor/node_modules/fibers
> node build.js || nodejs build.js


module.js:340
    throw err;
          ^
Error: Cannot find module '/root/.nvm/v0.10.40/lib/node_modules/iron-meteor/node_modules/fibers/build.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

module.js:340
    throw err;
          ^
Error: Cannot find module '/root/.nvm/v0.10.40/lib/node_modules/iron-meteor/node_modules/fibers/build.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

npm ERR! fibers@1.0.7 install: `node build.js || nodejs build.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the fibers@1.0.7 install script.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-57-generic
npm ERR! command "/root/.nvm/v0.10.40/bin/node" "/root/.nvm/v0.10.40/bin/npm" "install" "-g" "iron-meteor"
npm ERR! cwd /var/www
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

As simple as that. What did I do wrong ?

**Comment by Loschcode** [comment]
alright my bad it was a sudo missing
