### ISSUE TITLE
--css option does not work with stylus, but --cssresource does

### ISSUE THREAD

**Issue by nidem** [iron-meteor/iron-cli#235]
I get an error when using --css=stylus

```
$ iron create test --css=stylus --js=coffee --html=jade
created test
/usr/local/lib/node_modules/iron-meteor/bin/iron:12
}).run();
   ^

Error: Unsported css engine: stylus
    at withValidation (/usr/local/lib/node_modules/iron-meteor/lib/config.js:43:11)
    at Object.CurrentConfig.withValue (/usr/local/lib/node_modules/iron-meteor/lib/config.js:64:17)
    at Command.<anonymous> (/usr/local/lib/node_modules/iron-meteor/lib/commands/init.js:58:24)
    at Command.invoke (/usr/local/lib/node_modules/iron-meteor/lib/command.js:111:26)
    at Command.<anonymous> (/usr/local/lib/node_modules/iron-meteor/lib/commands/create.js:15:37)
    at Command.invoke (/usr/local/lib/node_modules/iron-meteor/lib/command.js:111:26)
    at Command.run (/usr/local/lib/node_modules/iron-meteor/lib/command.js:91:21)
    at Command.runSubCommand (/usr/local/lib/node_modules/iron-meteor/lib/command.js:154:11)
    at Command.<anonymous> (/usr/local/lib/node_modules/iron-meteor/lib/iron.js:71:17)
    at Command.invoke (/usr/local/lib/node_modules/iron-meteor/lib/command.js:111:26)
```

Using --cssresource works fine

```
$ iron create test --cssresource=stylus --js=coffee --html=jade
created test/.iron
created test/.iron/config.json
...
```

--cssresource is not documented in the README.md

**Comment by chrisbutler** [comment]
@nidem using cssresource creates .styl files? i think it only 'works' because iron doesn't recognize that flag or use it in any way

it looks like we might have lost stylus support at some point, since i don't see the generators when looking at the code. but the config option would be this:

```iron create test --css=styl```

**Comment by chrisbutler** [comment]
this feature was never implemented, so the option has been removed.

happy to take a PR to add it though
