### ISSUE TITLE
'iron debug' causes "Unknown system errno 193" on Windows. 

### ISSUE THREAD

**Issue by andy4545** [iron-meteor/iron-cli#247]
Running command `iron debug` in the root project directory causes the following error.. 
If i run `meteor debug` from the app directory - all is ok. 

I see a similar issue #201 but see it was fixed. I am using the latest release of iron-cli 1.5.2

```
c:\ProgramData\chocolatey\lib\nodejs.commandline.0.10.33\tools\node_modules\iron-meteor\node_modules\fibers\future.js:300
                                                throw(ex);
                                                      ^
Error: spawn Unknown system errno 193
    at Object.Future.wait (c:\ProgramData\chocolatey\lib\nodejs.commandline.0.10.33\tools\node_modules\iron-meteor\node_modules\fibers\future.js:420:15)
    at syncSource (c:\ProgramData\chocolatey\lib\nodejs.commandline.0.10.33\tools\node_modules\iron-meteor\lib\commands\debug.js:10:17)
    at Command.<anonymous> (c:\ProgramData\chocolatey\lib\nodejs.commandline.0.10.33\tools\node_modules\iron-meteor\lib\commands\debug.js:30:5)
    at Command.invoke (c:\ProgramData\chocolatey\lib\nodejs.commandline.0.10.33\tools\node_modules\iron-meteor\lib\command.js:111:26)
    at Command.run (c:\ProgramData\chocolatey\lib\nodejs.commandline.0.10.33\tools\node_modules\iron-meteor\lib\command.js:91:21)
    at Command.runSubCommand (c:\ProgramData\chocolatey\lib\nodejs.commandline.0.10.33\tools\node_modules\iron-meteor\lib\command.js:154:11)
    at Command.<anonymous> (c:\ProgramData\chocolatey\lib\nodejs.commandline.0.10.33\tools\node_modules\iron-meteor\lib\iron.js:71:17)
    at Command.invoke (c:\ProgramData\chocolatey\lib\nodejs.commandline.0.10.33\tools\node_modules\iron-meteor\lib\command.js:111:26)
    at Command.run (c:\ProgramData\chocolatey\lib\nodejs.commandline.0.10.33\tools\node_modules\iron-meteor\lib\command.js:91:21)
    at c:\ProgramData\chocolatey\lib\nodejs.commandline.0.10.33\tools\node_modules\iron-meteor\bin\iron:11:8
    - - - - -
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)
```

**Comment by chrisbutler** [comment]
@andy4545 this should be fixed in 1.7.0
