### ISSUE TITLE
create app throws EISDIR: illegal operation on a directory error in Meteor 1.3

### ISSUE THREAD

**Issue by myrtleTree33** [iron-meteor/iron-cli#249]
Hello, I am getting this issue in Meteor 1.4.

I tried bumping down the `iron-cli` version, but it still throws the same error.

Any idea?

```
joel@joel-Lenovo-Yoga-3-14:~/repos$ rm -rf myrtletree33Studios/ && iron create  myrtletree33Studios
created myrtletree33Studios
created myrtletree33Studios/.iron
created myrtletree33Studios/.iron/config.json
created myrtletree33Studios/bin
created myrtletree33Studios/bin/.gitkeep
created myrtletree33Studios/build
created myrtletree33Studios/build/.gitkeep
created myrtletree33Studios/build/README
created myrtletree33Studios/config
created myrtletree33Studios/config/.gitkeep
created myrtletree33Studios/config/development
created myrtletree33Studios/config/development/env.sh
created myrtletree33Studios/config/development/settings.json
created myrtletree33Studios/config/production
created myrtletree33Studios/config/production/env.sh
created myrtletree33Studios/config/production/settings.json
Creating project  app... /
/home/joel/.nvm/v6.2.2/lib/node_modules/iron-meteor/node_modules/fibers/future.js:267
						throw(ex);
						^

Error: EISDIR: illegal operation on a directory, unlink 'myrtletree33Studios/app/client'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:1083:18)
    at /home/joel/.nvm/v6.2.2/lib/node_modules/iron-meteor/lib/tools/meteor.js:35:10
    at Function._.each._.forEach (/home/joel/.nvm/v6.2.2/lib/node_modules/iron-meteor/node_modules/underscore/underscore.js:153:9)
    at Command.createEmptyMeteorProject (/home/joel/.nvm/v6.2.2/lib/node_modules/iron-meteor/lib/tools/meteor.js:32:7)
    at /home/joel/.nvm/v6.2.2/lib/node_modules/iron-meteor/lib/commands/init.js:63:10
    at Object.CurrentConfig.withValue (/home/joel/.nvm/v6.2.2/lib/node_modules/iron-meteor/lib/config.js:65:13)
    at Command.<anonymous> (/home/joel/.nvm/v6.2.2/lib/node_modules/iron-meteor/lib/commands/init.js:58:24)
    at Command.invoke (/home/joel/.nvm/v6.2.2/lib/node_modules/iron-meteor/lib/command.js:111:26)
    at Command.<anonymous> (/home/joel/.nvm/v6.2.2/lib/node_modules/iron-meteor/lib/commands/create.js:15:37)
```

**Comment by myrtleTree33** [comment]
Duplicate of #233
