### ISSUE TITLE
Error installing "iron create" on Windows Box with Preview 0.1.7

### ISSUE THREAD

**Issue by landmaxcanada** [iron-meteor/iron-cli#97]
Following the tutorial at Evented Mind (https://www.eventedmind.com/classes/build-a-multi-page-app-with-iron-meteor-6737880d). There are some errors:

### 1) During "create" 

>D:\_MeteorLocal\Evented Mind> iron create todos --css=less
created todos
created todos\.iron
created todos\.iron\config.json
created todos\build
created todos\build\README
created todos\config
created todos\config\development
created todos\config\development\env.sh
created todos\config\development\settings.json
Creating project  app... -

>C:\Users\Dev\AppData\Roaming\npm\node_modules\iron-meteor\node_modules\fibers\future.js:206
                                                throw(ex);
                                                      ^
>Error: Command failed: 'rm' is not recognized as an internal or external command,
    at Object.Future.wait (C:\Users\Dev\AppData\Roaming\npm\node_modules\iron-meteor\node_modules\fibers\future.js:326:1
5)
    at Command.execSync (C:\Users\Dev\AppData\Roaming\npm\node_modules\iron-meteor\lib\tools\exec_sync.js:22:17)
    at Command.createEmptyMeteorProject (C:\Users\Dev\AppData\Roaming\npm\node_modules\iron-meteor\lib\tools\meteor.js:3
0:10)
    at C:\Users\Dev\AppData\Roaming\npm\node_modules\iron-meteor\lib\commands\init.js:56:10
    at Object.CurrentConfig.withValue (C:\Users\Dev\AppData\Roaming\npm\node_modules\iron-meteor\lib\config.js:65:13)
    at Command.<anonymous> (C:\Users\Dev\AppData\Roaming\npm\node_modules\iron-meteor\lib\commands\init.js:51:24)
    at Command.invoke (C:\Users\Dev\AppData\Roaming\npm\node_modules\iron-meteor\lib\command.js:111:26)
    at Command.<anonymous> (C:\Users\Dev\AppData\Roaming\npm\node_modules\iron-meteor\lib\commands\create.js:15:37)
    at Command.invoke (C:\Users\Dev\AppData\Roaming\npm\node_modules\iron-meteor\lib\command.js:111:26)
    at Command.run (C:\Users\Dev\AppData\Roaming\npm\node_modules\iron-meteor\lib\command.js:91:21)
    - - - - -
operable program or batch file.
at ChildProcess.exithandler (child_process.js:658:15)
at ChildProcess.emit (events.js:98:17)
at maybeClose (child_process.js:766:16)
at Process.ChildProcess._handle.onexit (child_process.js:833:5)

## 1 - Workaround 
Ran command again and the directory structure was created.

### 2) Running Iron Command

The iron command fails
> D:\_MeteorLocal\Evented Mind\todos>iron

> C:\Users\Dev\AppData\Roaming\npm\node_modules\iron-meteor\node_modules\fibers\future.js:206
                                                throw(ex);
                                                      ^
> Error: spawn Unknown system errno 193
    at Object.Future.wait (C:\Users\Dev\AppData\Roaming\npm\node_modules\iron-meteor\node_modules\fibers\future.js:326:1
5)
    at syncSource (C:\Users\Dev\AppData\Roaming\npm\node_modules\iron-meteor\lib\commands\run.js:10:17)
    at Command.<anonymous> (C:\Users\Dev\AppData\Roaming\npm\node_modules\iron-meteor\lib\commands\run.js:30:5)
    at Command.invoke (C:\Users\Dev\AppData\Roaming\npm\node_modules\iron-meteor\lib\command.js:111:26)
    at Command.run (C:\Users\Dev\AppData\Roaming\npm\node_modules\iron-meteor\lib\command.js:91:21)
    at Command.runSubCommand (C:\Users\Dev\AppData\Roaming\npm\node_modules\iron-meteor\lib\command.js:154:11)
    at Command.<anonymous> (C:\Users\Dev\AppData\Roaming\npm\node_modules\iron-meteor\lib\iron.js:66:17)
    at Command.invoke (C:\Users\Dev\AppData\Roaming\npm\node_modules\iron-meteor\lib\command.js:111:26)
    at Command.run (C:\Users\Dev\AppData\Roaming\npm\node_modules\iron-meteor\lib\command.js:91:21)
    at C:\Users\Dev\AppData\Roaming\npm\node_modules\iron-meteor\bin\iron:11:8
    - - - - -
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

## 2 - Workaround 
Run meteor command from the app directory

**Comment by cmather** [comment]
Whoops. Got a little sloppy with executing linux commands during create. I'm noticing two issues:

1. lib/tools/meteor.js createEmptyMeteorProject line 30 is calling the `rm` command. Should use the node stdlib instead.

2. It looks like the `todos/.iron` folder is instead being created at `todos.iron`.

Not sure what the second issue in your list is. Let me try fixing the first couple of issues and maybe that'll fix it.

**Comment by cmather** [comment]
Hey @landmaxcanada, can you try a development version of this and see if the create command works for you now?

```
> git clone https://github.com/iron-meteor/iron-cli.git ~/src/iron-cli
> cd ~/src/iron-cli
> npm install
> npm link
> mkdir -p ~/src/tmp
> cd ~/src/tmp
> iron create new-project
```

Change linux commands to windows equivalents of course :).

**Comment by cmather** [comment]
I think this is fixed. Let me know if not.
