### ISSUE TITLE
Yosemite+Node 0.11 / 0.10 / 0.10.29

### ISSUE THREAD

**Issue by oedemis** [iron-meteor/iron-cli#99]
I have installed the npm install -g orefalo/iron-cli Verson and it outputs the following error if scaffold the app: "Error creating file ../../../../... Error: EISDIR, illegal operation on a directory '/Users/..."
"Error: EISDIR, illegal operation on a directory '/Users/ooedemis/Desktop/Studium/tutorials/js'
    at Object.fs.openSync (fs.js:413:18)
    at Object.fs.writeFileSync (fs.js:952:15)
    at Generator.createFile (/usr/local/lib/node_modules/iron-meteor/lib/tools/file_system.js:34:8)
    at Generator.template (/usr/local/lib/node_modules/iron-meteor/lib/tools/file_system.js:368:18)
    at Generator.<anonymous> (/usr/local/lib/node_modules/iron-meteor/lib/generators/template.js:31:8)
    at Generator.invoke (/usr/local/lib/node_modules/iron-meteor/lib/command.js:111:26)
    at /usr/local/lib/node_modules/iron-meteor/lib/generator.js:89:34
    at Object.CurrentConfig.withValue (/usr/local/lib/node_modules/iron-meteor/lib/config.js:65:13)
    at Object.CurrentConfig.withConfigFile (/usr/local/lib/node_modules/iron-meteor/lib/config.js:96:17)
    at /usr/local/lib/node_modules/iron-meteor/lib/generator.js:88:21"

 
The approach:
git clone git@github.com:iron-meteor/iron-cli.git
cd iron-cli 
npm install 
npm link
 with node 0.12
 installs correctly, but if i type in the console "iron" the following error was produced: 
throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibe
          ^
Error: `/Users/ooedemis/Desktop/Studium/tutorials/js/meteor/src/iron-cli/node_modules/fibers/bin/darwin-x64-v8-3.28/fibers.node` is missing. Try reinstalling `node-fibers`?
    at Object.<anonymous> (/Users/ooedemis/Desktop/Studium/tutorials/js/meteor/src/iron-cli/node_modules/fibers/fibers.js:13:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/ooedemis/Desktop/Studium/tutorials/js/meteor/src/iron-cli/bin/iron:3:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

And with: npm install -g n +  n 0.10.29 the first error outputs is produced.

**Comment by oedemis** [comment]
Solved, if you install npm install -g orefalo/iron-cli  with fiber 1.0.5 and you are not in a directory structure where a dir. name is "js" it actually works.

**Comment by hvtor** [comment]
➜  ~  npm install -g fibers
➜  ~  npm install -g orefalo/iron-cli

That worked great! 

Thanks!

**Comment by scott-mcpherson** [comment]
Sorry about the late reply. Glad you guys got it figured out.

**Comment by cmather** [comment]
We should just update this to the latest version of fibers and node. I was hoping to get to it but didn't. Scott if you have 15 min this weekend to do it before me go ahead! Otherwise I'll try to knock it out Monday.

**Comment by scott-mcpherson** [comment]
I'm probably overlooking something here, but doesn't iron-cli just use whatever version of node is installed on the machine @cmather ? We just need to update fibers to 1.0.5, right?

**Comment by cmather** [comment]
Yeah I think that's right. I was getting my wires crossed earlier.

**Comment by eposschweiz** [comment]
i still have this problem 
Error: EISDIR, illegal operation on a directory '/Users/.... on any mac i try to use iron-meteor and cannot solve it. i really need help on this

**Comment by labolado** [comment]
I have this problem too.
